### ISSUE TITLE
No module named paypal.standard on uwsgi

### ISSUE THREAD

**Issue by luanfonceca** [spookylukey/django-paypal#140]
Hi folks, i am in the middle of a deploy with my code using the `django-paypal`, but when i tried to restart the uwsgi i received the following error:

```
Traceback (most recent call last):
  File "/home/168horas/web168h/wsgi.py", line 22, in <module>
    application = Cling(get_wsgi_application())
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named paypal.standard
```

I am using `Django==1.8.4` and `django-paypal==0.3.1`, the most disturbing thing is that when i ran a `./manage.py runserver 0.0.0.0:8000` for instance the code works like a charm.

Thanks in advance for any tip on that.

**Comment by spookylukey** [comment]
This sounds like either it is not installed properly, or an import cycle. These can be difficult to track down, I'm afraid, but there is little I can do to help debug it. This might help: http://stackoverflow.com/questions/9098787/tool-for-pinpointing-circular-imports-in-python-django and http://stackoverflow.com/questions/744373/circular-or-cyclic-imports-in-python

If you find that the import cycle is actually in django-paypal, please re-open.

**Comment by luanfonceca** [comment]
Thats okay @spookylukey, thanks for the links.

o/

**Comment by fahtima** [comment]
You just need to install django-paypal. `pip install django-paypal`
