### ISSUE TITLE
TypeError: data must be a byte string

### ISSUE THREAD

**Issue by joaolsilva** [spookylukey/django-paypal#141]
When receiving an IPN payment signal the data doesn't reach the view because it crashes (returning 500 internal server error).

I'm using:

Debian Jessie (fully updated)

* django-paypal 0.3.1
* Django 1.9.4
* Python 2.7.9
* requests 2.9.1

Traceback follows:

ERROR [django.request:284] Internal Server Error: /paypal/
Traceback (most recent call last):
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/django/views/decorators/http.py", line 42, in inner
    return func(request, *args, **kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/paypal/standard/ipn/views.py", line 86, in ipn
    ipn_obj.verify(item_check_callable)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/paypal/standard/models.py", line 334, in verify
    self.response = self._postback().decode('ascii')
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/paypal/standard/ipn/models.py", line 26, in _postback
    return requests.post(self.get_endpoint(), data=b("cmd=_notify-validate&%s" % self.query)).content
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 854, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 218, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/home/username/.virtualenvs/project-name/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 207, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 947, in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string

**Comment by joaolsilva** [comment]
Solved by installing a new version of pyOpenSSL (now16.0.0)
* apt-get install libffi-dev
* pip install pyOpenSSL
