### ISSUE TITLE
Re add support for USE_TZ=False

### ISSUE THREAD

**Issue by Gromph** [spookylukey/django-paypal#166]
After upgrading from  0.2.7 to 0.3.3 IPNs started getting this exception:
`Traceback (most recent call last):
  File "C:\Projects\plaza\App\Payments\tests.py", line 53, in test_payment_paypal_ipn
    response = self.client.post("/payments/data/pay_pal_payment/", sData, content_type="application/x-www-form-urlencoded");
  File "C:\Python27\lib\site-packages\django\test\client.py", line 541, in post
    secure=secure, **extra)
  File "C:\Python27\lib\site-packages\django\test\client.py", line 343, in post
    secure=secure, **extra)
  File "C:\Python27\lib\site-packages\django\test\client.py", line 409, in generic
    return self.request(**r)
  File "C:\Python27\lib\site-packages\django\test\client.py", line 494, in request
    six.reraise(*exc_info)
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\paypal\standard\ipn\views.py", line 96, in ipn
    ipn_obj.verify()
  File "C:\Python27\lib\site-packages\paypal\standard\models.py", line 364, in verify
    self.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1053, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1006, in as_sql
    for obj in self.query.objs
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 945, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 755, in get_db_prep_save
    prepared=False)
  File "C:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 1439, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "C:\Python27\lib\site-packages\django\db\backends\mysql\operations.py", line 149, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

`

I tracked it down to PayPalDateTimeField stopped checking for settings.USE_TZ in this change:
https://github.com/spookylukey/django-paypal/commit/9158a9ed7620a04440af574d65cb3da9a1a76c9b

**Comment by spookylukey** [comment]
@Gromph 

Thanks for the report, and for tracking down the commit that caused the regression. I should have fixed the issue in latest commits to master, as indicated above. I've also added test suite configurations that run with USE_TZ=False, so this regression should not happen again.

Please test using MySQL - I have only tested using SQLite. I think the test suite coverage is enough to ensure that the timezone conversion is done correctly (i.e. to UTC), but you might want to check that. It's possible that the previous (0.2.7) behaviour was incorrect with regard to these dates if you had USE_TZ=False, I don't know. It was a bit messed up because of hacking around PayPal strangeness.

If you give me the go ahead after testing, I'll release a 0.3.4 with these changes.

**Comment by Gromph** [comment]
Yup it looks good now. Thanks for the quick fixes.

**Comment by spookylukey** [comment]
Thanks for getting back to me, version 0.3.6 is now on PyPI
