### ISSUE TITLE
certificate verify failed 

### ISSUE THREAD

**Issue by comalex** [spookylukey/django-paypal#93]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "./paypal/standard/ipn/views.py", line 58, in ipn
    ipn_obj.verify(item_check_callable)
  File "./paypal/standard/ipn/models.py", line 38, in verify
    self.response = self._postback()
  File "./paypal/standard/ipn/models.py", line 21, in _postback
    return urllib2.urlopen(self.get_endpoint(), "cmd=_notify-validate&%s" % self.query).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

**Comment by spookylukey** [comment]
Please upgrade to latest django-paypal, which uses `requests` rather than `urllib2` and probably won't have this problem. It might also be a problem with certificates installed on your machine.
